SELECT_A_MONTH = 'Select a month'
PICK_DAY = 'Pick a day or a few days'
ADD_INTERVAL = 'Add an interval between clients, this will help us adjust your work schedule for ease of note-taking'
PICK_ONE_DAY = 'Pick one of the days'
SELECT_WORKING_DAY = 'Select the length of the working day'
INTERVAL_CANNOT_BE_0H_OM = 'The interval cannot be 0h 0m'
CHOOSE_TWO_VALUE = 'There are two values to choose from'
ADD_START_TIME = 'Add the start time of the working day'
ADD_END_TIME = 'Add the time of the end of the working day'
TIME_ADDED = 'Time successfully added!'
TOTAL_OPERATING_TIME_LESS_INTERVAL = 'The total operating time cannot be less than the interval you have selected:'
SELECT_START_AND_END_WORKING_DAY = 'You have to select the start and end of the working day'
PICK_END_OF_THE_DAY = 'You have to pick the end of the day'
PICK_START_OF_THE_DAY = 'We have to choose the beginning of the work day'
CONTINUE = 'Continue'
RETURN = 'Return'
RETURN_ADMIN_PANEL = 'Admin panel'

ADD_BREAK_QUESTION = "Would you like to add a break?"
ADD_BREAK_ACTION = "Add break time"
ADD_BREAK_START_TIME = "Add break start time"
ADD_BREAK_END_TIME = "Add break end time"
BREAK_START_LESS_WORK_TIME = "Break start time cannot be less than work time"
BREAK_START_EXCEED_WORK_TIME = "Break start time cannot exceed work time"
BREAK_START_NOT_IN_WORK_INTERVAL = "Break start time not in working interval ({})"
BREAK_START_EXCEED_BREAK_END = "Break start time cannot be more than break end time ({})"
BREAK_END_EXCEED_WORK_TIME = "Break end time cannot exceed work time"
BREAK_END_LESS_WORK_TIME = "Break end time cannot be less work time"
BREAK_END_NOT_IN_WORK_INTERVAL = "Break end time not in working interval ({})"
BREAK_END_LESS_BREAK_START = "Break end time cannot be less than start time ({})"
NEXT_PAGE = 'next page'
PRIOR_PAGE = 'prior page'
CONTINUE_BUTTON_TXT = "Continue"
HOURS_LABEL = "Hours"
MINUTES_LABEL = "Minutes"
HOURS_STEP_LABEL_TEMPLATE = "{}h"
MINUTES_STEP_LABEL_TEMPLATE = "{}m"
HOUR_LABEL = "hour"
YES_LABEL = "YES"
NO_LABEL = 'NO'
HOUR_ABBREVIATION = "h"
HOUR_STEP_LABEL_TEMPLATE = "0{}h"
MINUTE_STEP_LABEL_TEMPLATE = "0{}m"
ENROLL_CLIENT = "Enroll the client"
OVERLAP_TIME_LABEL = "Overlap time"
EDIT_LABEL = "Edit"
