SELECT_ACTION = 'Выберите действие'
NOT_HAVE_CATEGORIES = 'Извините, нет созданных категорий, сперва создайте категорию'
ADD_NAME_CATEGORIES = 'Отправьте имя новой категории:'
CHANGE = 'Изменить'
SELECT_CATEGORY = 'Выберите категорию:'
REMOVE = 'Удалить'
SELECT = 'Выбрать'
