SELECT_SOCIAL_NETWORK = 'Выберите социальную сеть'
ADD_USERNAME = 'Введите имя пользователя'
confirm = 'Подтвердить'
change = 'Изменить'
remove = 'Удалить'
ENTER_ADDRESS = 'Введите ваш адрес'
SELECT_TO_CHANGE = 'Выберите для изменения'
ENTER_ADDITIONAL_SOCIAL_NETWORK = 'Выберите социальную сеть для добавления'
