SELECT_A_MONTH = 'Выберите интересующий вас месяц \n🔹- текущий месяц'
SELECT_A_DAYS = 'Выберите интересующий вас день \n🔹- текущий день'
SELECT_A_DAYS_SHOW_ALERT = 'Выберите день для продолжения'
SLOT_MANAGEMENT = 'Управление расписанием'
NO_PRIOR_WORK_DAYS = "Отсутствуют ранее созданные рабочие дни"
NO_NEXT_WORK_DAYS = "Отсутствуют рабочие дни созданные позже"
SELECT_ACTION = "Выберите действие"
ENTER_NEW_START_END_TIME_CUR_SLOT = "Введите новое время начала и окончания текущего рабочего окна"
ENTER_NEW_START_TIME_CUR_SLOT = "Введите новое время начала текущего рабочего окна"
NEW_START_TIME_LESS_CUR_SLOT_TIME = "Новое время начала не может быть до начала текущего окна"
NEW_START_TIME_EQUAL_AFTER_CUR_SLOT_TIME = "Новое время начала не может быть равно или позже окончания текущего окна"

NEW_END_TIME_LESS_CUR_SLOT_TIME = "Новое время окончания не может быть после окончания текущего окна"
NEW_END_TIME_EQUAL_AFTER_CUR_SLOT_TIME = "Новое время окончания не может быть равно или перед началом текущего окна"

ENTER_NEW_END_TIME_CUR_SLOT = "Введите новое время окончания текущего рабочего окна"
SUCCESSFULLY = "Действие выполнено успешно"
CURRENT_WORK_TIME = "Текущее рабочее время: {} - {}"
START_TIME_END_TIME_SAME_ERROR = "Время начала и окончания не может совпадать"
NEW_START_TIME_OVERLAP_CUR = "Начало нового рабочего времени ({}) пересекается с текущим рабочим временем({} - {})"
NEW_END_TIME_LESS_CUR_TIME = "Новое время окончания работы ({}) не может быть до текущего времени начала ({})"
NOT_ALLOWED = "Не разрешено"
AVAILABLE = "Доступно"
OVERLAPPED = "Перекрыто"
BREAK = "Перерыв"
ADD_NEW_WORK_TIME_INTERVAL = "Добавить время"
RETURN_SLOT_ACTIVE = "Сделать активным"
PAGE = "Стр {}/{}"
MAKE_SLOT_ACTIVE = "Сделать активным"
