SELECT_A_MONTH = 'Выберите месяц'
PICK_DAY = 'Выберите один или несколько дней'
ADD_INTERVAL = 'Выберите минимальный рабочий интервал, время самой короткой услуги'
PICK_ONE_DAY = 'Выберите один или несколько дней для продолжения'
SELECT_WORKING_DAY = 'Выберите время начала и конца рабочего дня'
INTERVAL_CANNOT_BE_0H_OM = 'Минимальный рабочий интервал не может быть 00:00'
CHOOSE_TWO_VALUE = 'Выберите значение часов и значение минут'
ADD_START_TIME = 'Выберите время начала рабочего дня'
ADD_END_TIME = 'Выберите время конца рабочего дня'
TIME_ADDED = 'Окошки рабочего времени успешно созданы'
TOTAL_OPERATING_TIME_LESS_INTERVAL = 'Общее рабочее время должно быть больше минимального рабочего интервала:'
SELECT_START_AND_END_WORKING_DAY = 'Выберите время начала и конца рабочего дня для продолжения'
PICK_END_OF_THE_DAY = 'Выберите время конца рабочего дня для продолжения'
PICK_START_OF_THE_DAY = 'Выберите время начала рабочего дня для продолжения'
CONTINUED = 'Продолжить'
RETURN = 'Вернуться'
RETURN_ADMIN_PANEL = 'Админ - Меню'

ADD_BREAK_QUESTION = "Вы хотите добавить перерыв?"
ADD_BREAK_ACTION = "Добавить перерыв"
ADD_BREAK_START_TIME = "Выберите время начала перерыва"
ADD_BREAK_END_TIME = "Выберите время окончания перерыва"
BREAK_START_LESS_WORK_TIME = "Начало перерыва не может быть раньше начала рабочего дня"
BREAK_START_EXCEED_WORK_TIME = "Начало перерыва не может быть позже окончания рабочего дня"
BREAK_START_NOT_IN_WORK_INTERVAL = "Начало перерыва не попадает в рабочий интервал ({})"
BREAK_START_EXCEED_BREAK_END = "Начало перерыва не может быть позже окончания перерыва ({})"
BREAK_END_EXCEED_WORK_TIME = "Конец перерыва не может быть позже окончания рабочего дня"
BREAK_END_LESS_WORK_TIME = "Окончание перерыва не может быть раньше начала рабочего дня"
BREAK_END_NOT_IN_WORK_INTERVAL = "Окончание перерыва не попадает в рабочий интервал ({})"
BREAK_END_LESS_BREAK_START = "Окончание перерыва не может быть раньше начала перерыва ({})"
NEXT_PAGE = 'следующая страница'
PRIOR_PAGE = 'предыдущая страница'
CONTINUE_BUTTON_TXT = "Продолжить"
HOURS_LABEL = "Часы"
MINUTES_LABEL = "Минуты"
HOURS_STEP_LABEL_TEMPLATE = "{}ч"
MINUTES_STEP_LABEL_TEMPLATE = "{}м"
HOUR_LABEL = "час"
YES_LABEL = "ДА"
NO_LABEL = 'НЕТ'
HOUR_ABBREVIATION = "ч"
HOUR_STEP_LABEL_TEMPLATE = "0{}ч"
MINUTE_STEP_LABEL_TEMPLATE = "0{}м"
ENROLL_CLIENT = "Записать клиента"
OVERLAP_TIME_LABEL = "Время перекрытия"
EDIT_LABEL = "Изменить"
