SELECT_A_MONTH = 'Выберите месяц'
PICK_DAY = 'Выберите один или несколько дней'
ADD_INTERVAL = 'Выберите минимальный рабочий интервал, время самой короткой услуги'
PICK_ONE_DAY = 'Выберите один или несколько дней для продолжения'
SELECT_WORKING_DAY = 'Выберите время начала и конца рабочего дня'
INTERVAL_CANNOT_BE_0H_OM = 'Минимальный рабочий интервал не может быть 00:00'
CHOOSE_TWO_VALUE = 'Выберите значение часов и значение минут'
ADD_START_TIME = 'Выберите время начала рабочего дня'
ADD_END_TIME = 'Выберите время конца рабочего дня'
TIME_ADDED = 'Окошки рабочего времени успешно созданы'
TOTAL_OPERATING_TIME_LESS_INTERVAL = 'Общее рабочее время должно быть больше минимального рабочего интервала:'
SELECT_START_AND_END_WORKING_DAY = 'Выберите время начала и конца рабочего дня для продолжения'
PICK_END_OF_THE_DAY = 'Выберите время конца рабочего дня для продолжения'
PICK_START_OF_THE_DAY = 'Выберите время начала рабочего дня для продолжения'
CONTINUED = 'Продолжить'
RETURN = 'Вернуться'
RETURN_ADMIN_PANEL = 'Панель админа'
add_break_prompt = "Would you like to add a break?"
add_break_time_prompt = "Add break time"
add_break_start_time_prompt = "Add break start time"
add_break_end_time_prompt = "Add break end time"
break_cannot_start_before_workday = "Break cannot start earlier than the workday start."
break_cannot_start_after_workday_end = "Break cannot start after the workday end."
break_start_not_in_interval_prompt = "Break start does not fall within the selected interval {}."
break_start_after_end_error = "Cannot set break start time after break end time {}"
break_cannot_end_after_workday_end = "Break cannot end after the workday end."
break_end_before_workday_start_error = "Break end cannot be earlier than the workday start."
break_end_not_in_interval_error = "Break end does not fall within the selected interval {}."
break_end_before_start_error = "Your break end time is set before the start time {}."
next_action = 'next'
back_action = 'back'
continue_button_text = "Continue"
hours_label = "Hours"
minutes_label = "Minutes"
hours_step_label_template = "{}h"
minutes_step_label_template = "{}m"
hour_label = "hour"
yes_label = "yes"
no_label = 'no'
hour_abbreviation = "h"
hour_step_label_template = "0{}h"
minute_step_label_template = "0{}m"
book_client_label = "Book client."
overlap_time_label = "Overlap time"
edit_label = "Edit"
