SELECT_A_MONTH = 'Select a month.'
PICK_DAY = 'Pick a day or a few days.'
ADD_INTERVAL = 'Add an interval between clients, this will help us adjust your work schedule for ease of note-taking.'
PICK_ONE_DAY = 'Pick one of the days.'
SELECT_WORKING_DAY = 'Select the length of the working day.'
INTERVAL_CANNOT_BE_0H_OM = 'The interval cannot be 0h 0m.'
CHOOSE_TWO_VALUE = 'There are two values to choose from.'
ADD_START_TIME = 'Add the start time of the working day.'
ADD_END_TIME = 'Add the time of the end of the working day.'
TIME_ADDED = 'Time successfully added!'
TOTAL_OPERATING_TIME_LESS_INTERVAL = 'The total operating time cannot be less than the interval you have selected:'
SELECT_START_AND_END_WORKING_DAY = 'You have to select the start and end of the working day.'
PICK_END_OF_THE_DAY = 'You have to pick the end of the day.'
PICK_START_OF_THE_DAY = 'We have to choose the beginning of the work day.'
CONTINUED = 'To be continued.'
RETURN = 'Return'
RETURN_ADMIN_PANEL = 'Admin panel'
add_break_prompt = "Would you like to add a break?"
add_break_time_prompt = "Add break time"
add_break_start_time_prompt = "Add break start time"
add_break_end_time_prompt = "Add break end time"
break_cannot_start_before_workday = "Break cannot start earlier than the workday start."
break_cannot_start_after_workday_end = "Break cannot start after the workday end."
break_start_not_in_interval_prompt = "Break start does not fall within the selected interval {}."
break_start_after_end_error = "Cannot set break start time after break end time {}"
break_cannot_end_after_workday_end = "Break cannot end after the workday end."
break_end_before_workday_start_error = "Break end cannot be earlier than the workday start."
break_end_not_in_interval_error = "Break end does not fall within the selected interval {}."
break_end_before_start_error = "Your break end time is set before the start time {}."
next_action = 'next'
back_action = 'back'
continue_button_text = "Continue"
hours_label = "Hours"
minutes_label = "Minutes"
hours_step_label_template = "{}h"
minutes_step_label_template = "{}m"
hour_label = "hour"
yes_label = "yes"
no_label = 'no'
hour_abbreviation = "h"
hour_step_label_template = "0{}h"
minute_step_label_template = "0{}m"
book_client_label = "Book client."
overlap_time_label = "Overlap time"
edit_label = "Edit"
